/**
* This code was generated by v0 by Vercel.
* @see https://v0.dev/t/XcnmwBzCOED
* Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
*/

/** Add fonts into your Next.js project:

import { Libre_Franklin } from 'next/font/google'
import { Chivo } from 'next/font/google'

libre_franklin({
  subsets: ['latin'],
  display: 'swap',
})

chivo({
  subsets: ['latin'],
  display: 'swap',
})

To read more about using these font, please visit the Next.js documentation:
- App Directory: https://nextjs.org/docs/app/building-your-application/optimizing/fonts
- Pages Directory: https://nextjs.org/docs/pages/building-your-application/optimizing/fonts
**/
"use client"

import { useState } from "react"
import { Avatar, AvatarImage, AvatarFallback } from "@/components/ui/avatar"
import { Button } from "@/components/ui/button"
import Link from "next/link"

export function Component() {
  const [showMuseumOptions, setShowMuseumOptions] = useState(false)
  return (
    <div className="flex flex-col items-center justify-center h-screen bg-gradient-to-br from-primary to-primary-foreground">
      <div className="bg-background rounded-xl shadow-lg w-full max-w-md">
        <div className="flex items-center justify-between px-4 py-3 bg-primary text-primary-foreground rounded-t-xl">
          <h2 className="text-lg font-semibold">AI Assistant</h2>
          <Avatar className="w-8 h-8 border">
            <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
            <AvatarFallback>AI</AvatarFallback>
          </Avatar>
        </div>
        <div className="h-[400px] overflow-y-auto px-4 py-6 space-y-4">
          <div className="flex items-start gap-3">
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
              <AvatarFallback>AI</AvatarFallback>
            </Avatar>
            <div className="bg-muted rounded-lg px-4 py-2 max-w-[70%]">
              <p>Hello, how can I assist you today?</p>
            </div>
          </div>
          <div className="flex items-start gap-3 justify-end">
            <div className="bg-primary text-primary-foreground rounded-lg px-4 py-2 max-w-[70%]">
              <Button onClick={() => setShowMuseumOptions(true)}>Select Museum</Button>
            </div>
            <Avatar className="w-8 h-8 border">
              <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
              <AvatarFallback>YO</AvatarFallback>
            </Avatar>
          </div>
          {showMuseumOptions && (
            <div className="flex items-start gap-3">
              <Avatar className="w-8 h-8 border">
                <AvatarImage src="/placeholder-user.jpg" alt="Avatar" />
                <AvatarFallback>AI</AvatarFallback>
              </Avatar>
              <div className="bg-muted rounded-lg px-4 py-2 max-w-[70%]">
                <p>Excellent choice! Here are 4 museum options for you to explore:</p>
                <div className="grid grid-cols-2 gap-2 mt-4">
                  <div>
                    <Link href="#" prefetch={false}>
                      <img
                        src="/placeholder.svg"
                        alt="Museum 1"
                        width={100}
                        height={100}
                        className="rounded-md"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }}
                      />
                    </Link>
                    <p className="text-sm text-muted-foreground mt-1">Museum 1</p>
                  </div>
                  <div>
                    <Link href="#" prefetch={false}>
                      <img
                        src="/placeholder.svg"
                        alt="Museum 2"
                        width={100}
                        height={100}
                        className="rounded-md"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }}
                      />
                    </Link>
                    <p className="text-sm text-muted-foreground mt-1">Museum 2</p>
                  </div>
                  <div>
                    <Link href="#" prefetch={false}>
                      <img
                        src="/placeholder.svg"
                        alt="Museum 3"
                        width={100}
                        height={100}
                        className="rounded-md"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }}
                      />
                    </Link>
                    <p className="text-sm text-muted-foreground mt-1">Museum 3</p>
                  </div>
                  <div>
                    <Link href="#" prefetch={false}>
                      <img
                        src="/placeholder.svg"
                        alt="Museum 4"
                        width={100}
                        height={100}
                        className="rounded-md"
                        style={{ aspectRatio: "100/100", objectFit: "cover" }}
                      />
                    </Link>
                    <p className="text-sm text-muted-foreground mt-1">Museum 4</p>
                  </div>
                </div>
              </div>
            </div>
          )}
        </div>
      </div>
    </div>
  )
}
